name: WebProxy

on:
  workflow_dispatch:

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Run
        run: |
          sudo apt update
          sudo apt install -y nginx curl
          sudo rm -rf /var/www/html/*
          sudo wget -O /var/www/html/index.html https://raw.githubusercontent.com/Everywhere-Pro/Fa/main/index.html 2>/dev/null || sudo wget -O /var/www/html/index.html https://raw.githubusercontent.com/namaka-media/browser/main/index.html 2>/dev/null
          sudo service nginx start
          npm install -g localtunnel
          lt --port 80 -o 2>&1 &
          sleep 10
          echo "==========================="
          echo "لینک خود را از خطوط بالا بردارید"
          echo "==========================="
          sleep 21600
